## 1)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## 2)

The way to to convert an input data X to corresponding nonnegative data is to use scaling. To ensure that it is nonnegative, a good scalar to use is the MinMaxScalar because it transforms the data [0,1]. 

#### Example

In [ ]:
from sklearn.preprocessing import MinMaxScaler
X = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
scaler_minmax = MinMaxScaler()
X_minmax = scaler_minmax.fit_transform(X)
print(X_minmax)

## 3)

SVD, singular-value decomposition is the factorization of some matrix, A, into its product matrices, USV^t. In these product matrices, U is an orthogonal matrix whose columns are the left singular vectors. S is a diagonal matrix of singular values. Finally, V^t's columns for the basis for the row space of A. It can be used for image compression by approximating the original image by dropping the singular values, decreasing the size of the image while maintaining an approximation. Basically, it simplifies the noise from the image.

## 4)

In [15]:
import numpy as np

def VCR(data):
    U, s, V = np.linalg.svd(data)
    vcr = s[0] / np.sum(s)

    return vcr

In [3]:
A = np.array([[1, 0], [8, 2], [9, -7]])  

B = np.array([[0.3, 0.7, 1], [1.2, 0.9, -0.98]])  


C = np.dot(A, B)  
VCR = VCR(C) 

print("Matrix C:\n", C)
print("VCR of C:", VCR)

Matrix C:
 [[ 3.00000000e-01  7.00000000e-01  1.00000000e+00]
 [ 4.80000000e+00  7.40000000e+00  6.04000000e+00]
 [-5.70000000e+00 -3.33066907e-16  1.58600000e+01]]
VCR of C: 0.6486611716159791


## 5)

In [5]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [21]:
iris = load_iris()
X = iris.data

scaler_standard = StandardScaler()
X_standard = scaler_standard.fit_transform(X)

scaler_minmax = MinMaxScaler()
X_minmax = scaler_minmax.fit_transform(X)


VCR_standard = VCR(X_standard)
print("VCR of Iris data with Standard Scaler:", VCR_standard)


VCR_minmax = VCR(X_minmax)
print("VCR of Iris data with MinMax Scaler:", VCR_minmax)

VCR of Iris data with Standard Scaler: 0.5352971788236239
VCR of Iris data with MinMax Scaler: 0.6800299414919467
